### PR TITLE
if min=0 value="0.00"

### PR DESCRIPTION
**Pull request by rkorsun-softheme**
thus .toFixed is not a function

### CODE REVIEW

**Comment by istvan-ujjmeszaros** [comment]
I can't reproduce the issue. Can you make a test on jsfiddle where the original bug is visible?

**Comment by rkorsun-softheme** [comment]
I'll try)

**Comment by istvan-ujjmeszaros** [comment]
I made a fiddle which you can easily modify:
https://jsfiddle.net/a9zwzp07/

**Comment by rkorsun-softheme** [comment]
really strange. I could not reproduce it on fiddle.
and have tried to do in on my.
please look at result
image

believe I do not hack settings manually

**Comment by istvan-ujjmeszaros** [comment]
It looks that the issue is `settings.min` is a string. Just set it to `0` instead of `"0.00"`, and it should work. I can't test it on jsfiddle as the site is down currently.

**Comment by istvan-ujjmeszaros** [comment]
Closing as I have successfully reproduced the error, which you can avoid if you use number instead of a string in the `min` value.

**Pull request closed without merging**
