### PR TITLE
Fixed an issue in the function `_checkVal` related to numeric to stri…

### PR DESCRIPTION
**Pull request by esapy**
Fixed a multiple `change` event that triggers multiple times even if the numeric value has not changed.

Refer to discussion
https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/issues/83

### CODE REVIEW

**Comment by esapy** [comment]
Hi @istvan-ujjmeszaros can you please merge?

**Comment by istvan-ujjmeszaros** [comment]
Thanks @esapy for creating a PR, I will test it later today and will publish a new version as well if it is working as expected.

**Comment by istvan-ujjmeszaros** [comment]
Just an update, I will merge it in the next 1-2 days (I just started to write tests and have to experiment with how JavaScript tests are working - I just got close to successfully run it).

**Comment by istvan-ujjmeszaros** [comment]
I have created a test for the case described in the issue, and the PR doesn't seem to solve it.
You can run the test locally with `npm test`, this one will fail:
https://github.com/esapy/bootstrap-touchspin/blob/numeric-conversion-comparison-fix/__tests__/test-html-page.test.js#L108

**Comment by istvan-ujjmeszaros** [comment]
I have decided to merge it as using parseFloat makes sense here. I am working on a fix for #83.

**Pull request merged**
